services:
  tmdbtovod:
    build:
      context: /mnt/user/appdata/tmdbtovod
      dockerfile: Dockerfile
    container_name: tmdbtovod
    ports:
      - "41063:80"
    volumes:
      - /mnt/user/appdata/tmdbtovod/TMDB-To-VOD-Playlist:/var/www/html:rw
    depends_on:
      - headlessvidx
    restart: unless-stopped

  headlessvidx:
    image: gogetta69/headlessvidx:latest
    container_name: HeadlessVidX
    ports:
      - "3202:3202"
    volumes:
      - files:/app/dict
    restart: unless-stopped

volumes:
  files: {}
